# Álgebra Lineal

El álgebra lineal es el estudio de vectores y ciertas reglas para maniuparlos.

### Vector
Son objetos que cumple con las siguientes condiciones:

    Se pueden sumar entre sí, y el resultado da otro vector.
    
   \begin{align}
       \textbf{x} + \textbf{y} = \textbf{z}
   \end{align}
    
    Pueden ser multiplicados por una escalar.
    
   \begin{align}
   \lambda \textbf{x}
   \end{align}
   
Ejemplos:

    Vector geométrico (dado por coordenadas en el plano cartesiano)
    
    Polinomios
    
    Señales de audio
    
    Elementos de  $\mathbb{R}^{n}$ 
    
En ML (Machine Learning) nos enfocamos en los elementos de $\mathbb{R}^{n}$

Una pregunta importante en el mundo de las matemáticas es:
##### ¿Cuál es el conjunto de todas las cosas que pueden resultar de mis operaciones propuestas?

Aplicandolo a álgebra lineal, sería,
##### ¿Cuál es el conjunto de vectores que puede resultar al comenzar con un pequeño conjunto de vectores, y sumarlos y escalarlos entre sí?

Y las respuesta es: *el espacio vectorial*.

In [4]:
# Creando un vector con numpy
import numpy as np

vector = np.array([0,1,2,3,4,5,6,7,8,9]) # 1d array

print(vector)
type(vector)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

## 1.1 Sistemas de Ecuaciones Lineales

Un sistema de ecuaciones lineales es una colección de una o más ecuaciones lineales que poseen el mismo conjunto de variables.

La forma general de un sistema de ecuaciones lineales es:

\begin{align}
a_{11}x_{1}  + \cdots + a_{in}x_{n} =  b_{1}\\
\hspace{-5.3cm}\vdots\\
a_{m1}x_{1}  + \cdots + a_{mn}x_{n} =  b_{n} 
\end{align}

$x$ son los valores desconocidos del sistema.

Resolver un sistema de ecuaciones lineales, nos lleva a tres posibles escenarios:

- Solución única
- Múltiples soluciones
- No hay solución


#### Interpretación geométrica de los sistemas de ecuaciones lineales
#### En $\mathbb{R}^{2}$
Cuando tenemos dos variables $x_{1}$ y  $x_{2}$ cada ecuación lineal representa una recta en el plano $x_{1}x_{2}$ y las posibles soluciones a esta ecuación lineal serían: linea (cuando ambas ecuaciones son iguales), un punto (cuando existe una única solución) y vacío (cuando las lineas son paralelas).

#### En $\mathbb{R}^{3}$
Cuando tenemos tres vaariables $x_{1}$, $x_{2}$  y  $x_{3}$ cada ecuación lineal representa un plano en el espacio $x_{1}x_{2}x_{3}$ y las posibles soluciones son: un plano, una línea, un punto y vacío (cuando los planos no tienen una intersección en común).

#### Notación compacta para resolver un sistema de ecuaciones lineales

El proceso implica conjuntar los coeficientes $a_{ij}$ en en vectores y conjuntar estos vectores en matrices.

\begin{align}
x_{1} \begin{bmatrix} a_{11} \\ \vdots\\ a_{m1} \end{bmatrix} + x_{2} \begin{bmatrix} a_{12} \\ \vdots\\ a_{m2}  +  
\end{bmatrix} + \cdots + x_{n} \begin{bmatrix} a_{1n} \\ \vdots\\ a_{mn}   \end{bmatrix}   = \begin{bmatrix} b_{1} \\ \vdots\\ b_{m} \end{bmatrix}
\end{align}

\begin{align}
\iff
\end{align}

\begin{align}
\begin{bmatrix}
a_{11} &  \dots & a_{1n} \\
\vdots & & \vdots\\
a_{m1} & \dots & a_{mn} 
\end{bmatrix} 
\begin{bmatrix}
x_{1} \\ \vdots\\ x_{n}
\end{bmatrix}
= \begin{bmatrix} b_{1} \\ \vdots\\ b_{m} \end{bmatrix}
\end{align}



Considerese el siguientes sistemas de ecuaciones lineales

\begin{align}
    4x + 3y + 2z = 25\\
    -2x + 2y + 3z = -10\\
    3x - 5y + 2z = -4\\
\end{align}




In [19]:
A = np.array([[4,3,2],[-2,2,3],[3,-5,2]])
B = np.array([25,-10,-4])
X = np.linalg.inv(A).dot(B)
print(A)
print("\n")
print(B)
print("\n")
print(X)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]


[ 25 -10  -4]


[ 5.  3. -2.]


## 2.2 Matrices

Una matriz $\textbf{A}$ es un conjunto ordenado de elementos de acuerdo a un esquema rectangular que consiste en *m* renglanos y *n* columnas.

Como se puede expresar en la expresión siguiente:

\begin{align}
A = \begin{bmatrix}
a_{11} & a_{12} & \dots & a_{1n} \\
a_{21} & a_{22} & \dots & a_{2n} \\
\vdots & \vdots & \vdots\\
a_{m1} & a_{m2} & \dots & a_{mn} 
\end{bmatrix} 
\end{align}

donde los valores $a_{ij}$ pertenecen a $\mathbb{R}$

In [10]:
# Escribir una matriz con Numpy

matrix_A = np.array([(1,2,3), (4,5,6), (7,8,9)]) # 2d array
# Representa una matriz de 3x3 

print(matrix_A)

type(matrix_A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

Como hemos visto, las matrices nos ayudan a escribir una forma compacta a los sistemas de ecuaciones lineales, por esa misma manera, juegan un papel muy importante en álgebra lineal.

#### Operaciones entre matrices

#### Suma

\begin{align}
A + B = \begin{bmatrix}
a_{11} &  \dots & a_{1n}  \\
\vdots & & \vdots\\
a_{m1} & \dots & a_{mn} 
\end{bmatrix} + \begin{bmatrix}
 b_{11} &  \dots &  b_{1n} \\
\vdots & & \vdots\\
 b_{m1}& \dots & b_{mn} 
\end{bmatrix} =\begin{bmatrix}
a_{11} + b_{11} &  \dots & a_{1n} + b_{1n} \\
\vdots & & \vdots\\
a_{m1} + b_{m1}& \dots & a_{mn} + b_{mn} 
\end{bmatrix}
\end{align}

In [22]:
# Suma de matrices

matrix_A = np.array([(1,2,3), (4,5,6), (7,8,9)])
matrix_B = np.array([(9,8,7),(6,5,4),(3,2,1)])

print(matrix_A)
print("\n")
print(matrix_B)
print("\n")
suma_A_B = matrix_A + matrix_B

print(suma_A_B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[9 8 7]
 [6 5 4]
 [3 2 1]]


[[10 10 10]
 [10 10 10]
 [10 10 10]]


#### Multiplicación
\begin{align}
c_{ij} = \sum_{l=1}^{n} a_{il} b_{lj}, \hspace{2cm} i = 1, \dots, m , \hspace{2cm}  j = 1, \dots, k
\end{align}

Cada matriz tiene dimensiones $mxn$, para que dos matrices A y B, puedan multiplicarse entre sí, sus dimensiones $mxn$, $kxl$, deben ser iguales en $n=k$.

In [23]:
matrix_A = np.array([(1,2,3), (4,5,6), (7,8,9)])
matrix_B = np.array([(9,8,7),(6,5,4),(3,2,1)])

print(matrix_A)
print("\n")
print(matrix_B)
print("\n")

product_AB = matrix_A*matrix_B

print(product_AB)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[9 8 7]
 [6 5 4]
 [3 2 1]]


[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
